-- Migration: adiciona coluna galeria[] e popula imagens dos manuais
ALTER TABLE public.processos ADD COLUMN IF NOT EXISTS galeria text[] NOT NULL DEFAULT '{}';

UPDATE public.processos SET galeria = ARRAY['/img/processos/deslocamento-vazio/001.jpg', '/img/processos/deslocamento-vazio/002.jpg', '/img/processos/deslocamento-vazio/003.jpg', '/img/processos/deslocamento-vazio/004.jpg', '/img/processos/deslocamento-vazio/005.jpg']
  WHERE titulo ILIKE '%Deslocamento Vazio%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/remessa-contas-pagar/001.jpg', '/img/processos/remessa-contas-pagar/002.jpg', '/img/processos/remessa-contas-pagar/003.jpg', '/img/processos/remessa-contas-pagar/004.jpg', '/img/processos/remessa-contas-pagar/005.jpg', '/img/processos/remessa-contas-pagar/006.jpg', '/img/processos/remessa-contas-pagar/007.jpg', '/img/processos/remessa-contas-pagar/008.jpg', '/img/processos/remessa-contas-pagar/009.jpg']
  WHERE titulo ILIKE '%Remessa Bancaria%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/remessa-contas-pagar/001.jpg', '/img/processos/remessa-contas-pagar/002.jpg', '/img/processos/remessa-contas-pagar/003.jpg', '/img/processos/remessa-contas-pagar/004.jpg', '/img/processos/remessa-contas-pagar/005.jpg', '/img/processos/remessa-contas-pagar/006.jpg', '/img/processos/remessa-contas-pagar/007.jpg', '/img/processos/remessa-contas-pagar/008.jpg', '/img/processos/remessa-contas-pagar/009.jpg']
  WHERE titulo ILIKE '%Remessa Bancária%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/relatorios/001.jpg', '/img/processos/relatorios/002.jpg', '/img/processos/relatorios/003.jpg', '/img/processos/relatorios/004.jpg', '/img/processos/relatorios/005.jpg', '/img/processos/relatorios/006.jpg', '/img/processos/relatorios/007.jpg', '/img/processos/relatorios/008.jpg', '/img/processos/relatorios/009.jpg', '/img/processos/relatorios/010.jpg', '/img/processos/relatorios/011.jpg', '/img/processos/relatorios/012.jpg', '/img/processos/relatorios/013.jpg', '/img/processos/relatorios/014.jpg', '/img/processos/relatorios/015.jpg', '/img/processos/relatorios/016.jpg']
  WHERE titulo ILIKE '%Cadastro e Emissao%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/relatorios/001.jpg', '/img/processos/relatorios/002.jpg', '/img/processos/relatorios/003.jpg', '/img/processos/relatorios/004.jpg', '/img/processos/relatorios/005.jpg', '/img/processos/relatorios/006.jpg', '/img/processos/relatorios/007.jpg', '/img/processos/relatorios/008.jpg', '/img/processos/relatorios/009.jpg', '/img/processos/relatorios/010.jpg', '/img/processos/relatorios/011.jpg', '/img/processos/relatorios/012.jpg', '/img/processos/relatorios/013.jpg', '/img/processos/relatorios/014.jpg', '/img/processos/relatorios/015.jpg', '/img/processos/relatorios/016.jpg']
  WHERE titulo ILIKE '%Cadastro e Emissão%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/expedicao/001.jpg', '/img/processos/expedicao/002.jpg', '/img/processos/expedicao/003.jpg', '/img/processos/expedicao/004.jpg', '/img/processos/expedicao/005.jpg', '/img/processos/expedicao/006.jpg', '/img/processos/expedicao/007.jpg', '/img/processos/expedicao/008.jpg', '/img/processos/expedicao/009.jpg', '/img/processos/expedicao/010.jpg', '/img/processos/expedicao/011.jpg', '/img/processos/expedicao/012.jpg', '/img/processos/expedicao/013.jpg', '/img/processos/expedicao/014.jpg', '/img/processos/expedicao/015.jpg', '/img/processos/expedicao/016.jpg', '/img/processos/expedicao/017.jpg', '/img/processos/expedicao/018.jpg', '/img/processos/expedicao/019.jpg', '/img/processos/expedicao/020.jpg', '/img/processos/expedicao/021.jpg', '/img/processos/expedicao/022.jpg', '/img/processos/expedicao/023.jpg', '/img/processos/expedicao/024.jpg', '/img/processos/expedicao/025.jpg', '/img/processos/expedicao/026.jpg', '/img/processos/expedicao/027.jpg', '/img/processos/expedicao/028.jpg', '/img/processos/expedicao/029.jpg', '/img/processos/expedicao/030.jpg', '/img/processos/expedicao/031.jpg', '/img/processos/expedicao/032.jpg', '/img/processos/expedicao/033.jpg', '/img/processos/expedicao/034.jpg', '/img/processos/expedicao/035.jpg', '/img/processos/expedicao/036.jpg', '/img/processos/expedicao/037.jpg', '/img/processos/expedicao/038.jpg', '/img/processos/expedicao/039.jpg', '/img/processos/expedicao/040.jpg', '/img/processos/expedicao/041.jpg', '/img/processos/expedicao/042.jpg', '/img/processos/expedicao/043.jpg']
  WHERE titulo ILIKE '%Expedicao por EDI%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/expedicao/001.jpg', '/img/processos/expedicao/002.jpg', '/img/processos/expedicao/003.jpg', '/img/processos/expedicao/004.jpg', '/img/processos/expedicao/005.jpg', '/img/processos/expedicao/006.jpg', '/img/processos/expedicao/007.jpg', '/img/processos/expedicao/008.jpg', '/img/processos/expedicao/009.jpg', '/img/processos/expedicao/010.jpg', '/img/processos/expedicao/011.jpg', '/img/processos/expedicao/012.jpg', '/img/processos/expedicao/013.jpg', '/img/processos/expedicao/014.jpg', '/img/processos/expedicao/015.jpg', '/img/processos/expedicao/016.jpg', '/img/processos/expedicao/017.jpg', '/img/processos/expedicao/018.jpg', '/img/processos/expedicao/019.jpg', '/img/processos/expedicao/020.jpg', '/img/processos/expedicao/021.jpg', '/img/processos/expedicao/022.jpg', '/img/processos/expedicao/023.jpg', '/img/processos/expedicao/024.jpg', '/img/processos/expedicao/025.jpg', '/img/processos/expedicao/026.jpg', '/img/processos/expedicao/027.jpg', '/img/processos/expedicao/028.jpg', '/img/processos/expedicao/029.jpg', '/img/processos/expedicao/030.jpg', '/img/processos/expedicao/031.jpg', '/img/processos/expedicao/032.jpg', '/img/processos/expedicao/033.jpg', '/img/processos/expedicao/034.jpg', '/img/processos/expedicao/035.jpg', '/img/processos/expedicao/036.jpg', '/img/processos/expedicao/037.jpg', '/img/processos/expedicao/038.jpg', '/img/processos/expedicao/039.jpg', '/img/processos/expedicao/040.jpg', '/img/processos/expedicao/041.jpg', '/img/processos/expedicao/042.jpg', '/img/processos/expedicao/043.jpg']
  WHERE titulo ILIKE '%Expedição por EDI%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/expedicao/001.jpg', '/img/processos/expedicao/002.jpg', '/img/processos/expedicao/003.jpg', '/img/processos/expedicao/004.jpg', '/img/processos/expedicao/005.jpg', '/img/processos/expedicao/006.jpg', '/img/processos/expedicao/007.jpg', '/img/processos/expedicao/008.jpg', '/img/processos/expedicao/009.jpg', '/img/processos/expedicao/010.jpg', '/img/processos/expedicao/011.jpg', '/img/processos/expedicao/012.jpg', '/img/processos/expedicao/013.jpg', '/img/processos/expedicao/014.jpg', '/img/processos/expedicao/015.jpg', '/img/processos/expedicao/016.jpg', '/img/processos/expedicao/017.jpg', '/img/processos/expedicao/018.jpg', '/img/processos/expedicao/019.jpg', '/img/processos/expedicao/020.jpg', '/img/processos/expedicao/021.jpg', '/img/processos/expedicao/022.jpg', '/img/processos/expedicao/023.jpg', '/img/processos/expedicao/024.jpg', '/img/processos/expedicao/025.jpg', '/img/processos/expedicao/026.jpg', '/img/processos/expedicao/027.jpg', '/img/processos/expedicao/028.jpg', '/img/processos/expedicao/029.jpg', '/img/processos/expedicao/030.jpg', '/img/processos/expedicao/031.jpg', '/img/processos/expedicao/032.jpg', '/img/processos/expedicao/033.jpg', '/img/processos/expedicao/034.jpg', '/img/processos/expedicao/035.jpg', '/img/processos/expedicao/036.jpg', '/img/processos/expedicao/037.jpg', '/img/processos/expedicao/038.jpg', '/img/processos/expedicao/039.jpg', '/img/processos/expedicao/040.jpg', '/img/processos/expedicao/041.jpg', '/img/processos/expedicao/042.jpg', '/img/processos/expedicao/043.jpg']
  WHERE titulo ILIKE '%Expedicao Manual%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/expedicao/001.jpg', '/img/processos/expedicao/002.jpg', '/img/processos/expedicao/003.jpg', '/img/processos/expedicao/004.jpg', '/img/processos/expedicao/005.jpg', '/img/processos/expedicao/006.jpg', '/img/processos/expedicao/007.jpg', '/img/processos/expedicao/008.jpg', '/img/processos/expedicao/009.jpg', '/img/processos/expedicao/010.jpg', '/img/processos/expedicao/011.jpg', '/img/processos/expedicao/012.jpg', '/img/processos/expedicao/013.jpg', '/img/processos/expedicao/014.jpg', '/img/processos/expedicao/015.jpg', '/img/processos/expedicao/016.jpg', '/img/processos/expedicao/017.jpg', '/img/processos/expedicao/018.jpg', '/img/processos/expedicao/019.jpg', '/img/processos/expedicao/020.jpg', '/img/processos/expedicao/021.jpg', '/img/processos/expedicao/022.jpg', '/img/processos/expedicao/023.jpg', '/img/processos/expedicao/024.jpg', '/img/processos/expedicao/025.jpg', '/img/processos/expedicao/026.jpg', '/img/processos/expedicao/027.jpg', '/img/processos/expedicao/028.jpg', '/img/processos/expedicao/029.jpg', '/img/processos/expedicao/030.jpg', '/img/processos/expedicao/031.jpg', '/img/processos/expedicao/032.jpg', '/img/processos/expedicao/033.jpg', '/img/processos/expedicao/034.jpg', '/img/processos/expedicao/035.jpg', '/img/processos/expedicao/036.jpg', '/img/processos/expedicao/037.jpg', '/img/processos/expedicao/038.jpg', '/img/processos/expedicao/039.jpg', '/img/processos/expedicao/040.jpg', '/img/processos/expedicao/041.jpg', '/img/processos/expedicao/042.jpg', '/img/processos/expedicao/043.jpg']
  WHERE titulo ILIKE '%Expedição Manual%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/controle-de-terceiros/001.jpg', '/img/processos/controle-de-terceiros/002.jpg', '/img/processos/controle-de-terceiros/003.jpg', '/img/processos/controle-de-terceiros/004.jpg', '/img/processos/controle-de-terceiros/005.jpg', '/img/processos/controle-de-terceiros/006.jpg', '/img/processos/controle-de-terceiros/007.jpg', '/img/processos/controle-de-terceiros/008.jpg', '/img/processos/controle-de-terceiros/009.jpg', '/img/processos/controle-de-terceiros/010.jpg', '/img/processos/controle-de-terceiros/011.jpg', '/img/processos/controle-de-terceiros/012.jpg', '/img/processos/controle-de-terceiros/013.jpg', '/img/processos/controle-de-terceiros/014.jpg', '/img/processos/controle-de-terceiros/015.jpg', '/img/processos/controle-de-terceiros/016.jpg', '/img/processos/controle-de-terceiros/017.jpg', '/img/processos/controle-de-terceiros/018.jpg', '/img/processos/controle-de-terceiros/019.jpg', '/img/processos/controle-de-terceiros/020.jpg', '/img/processos/controle-de-terceiros/021.jpg', '/img/processos/controle-de-terceiros/022.jpg', '/img/processos/controle-de-terceiros/023.jpg', '/img/processos/controle-de-terceiros/024.jpg', '/img/processos/controle-de-terceiros/025.jpg', '/img/processos/controle-de-terceiros/026.jpg', '/img/processos/controle-de-terceiros/027.jpg', '/img/processos/controle-de-terceiros/028.jpg', '/img/processos/controle-de-terceiros/029.jpg', '/img/processos/controle-de-terceiros/030.jpg', '/img/processos/controle-de-terceiros/031.jpg', '/img/processos/controle-de-terceiros/032.jpg', '/img/processos/controle-de-terceiros/033.jpg', '/img/processos/controle-de-terceiros/034.jpg', '/img/processos/controle-de-terceiros/035.jpg']
  WHERE titulo ILIKE '%Pagamento de Motoristas Terceiros%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/controle-de-terceiros/001.jpg', '/img/processos/controle-de-terceiros/002.jpg', '/img/processos/controle-de-terceiros/003.jpg', '/img/processos/controle-de-terceiros/004.jpg', '/img/processos/controle-de-terceiros/005.jpg', '/img/processos/controle-de-terceiros/006.jpg', '/img/processos/controle-de-terceiros/007.jpg', '/img/processos/controle-de-terceiros/008.jpg', '/img/processos/controle-de-terceiros/009.jpg', '/img/processos/controle-de-terceiros/010.jpg', '/img/processos/controle-de-terceiros/011.jpg', '/img/processos/controle-de-terceiros/012.jpg', '/img/processos/controle-de-terceiros/013.jpg', '/img/processos/controle-de-terceiros/014.jpg', '/img/processos/controle-de-terceiros/015.jpg', '/img/processos/controle-de-terceiros/016.jpg', '/img/processos/controle-de-terceiros/017.jpg', '/img/processos/controle-de-terceiros/018.jpg', '/img/processos/controle-de-terceiros/019.jpg', '/img/processos/controle-de-terceiros/020.jpg', '/img/processos/controle-de-terceiros/021.jpg', '/img/processos/controle-de-terceiros/022.jpg', '/img/processos/controle-de-terceiros/023.jpg', '/img/processos/controle-de-terceiros/024.jpg', '/img/processos/controle-de-terceiros/025.jpg', '/img/processos/controle-de-terceiros/026.jpg', '/img/processos/controle-de-terceiros/027.jpg', '/img/processos/controle-de-terceiros/028.jpg', '/img/processos/controle-de-terceiros/029.jpg', '/img/processos/controle-de-terceiros/030.jpg', '/img/processos/controle-de-terceiros/031.jpg', '/img/processos/controle-de-terceiros/032.jpg', '/img/processos/controle-de-terceiros/033.jpg', '/img/processos/controle-de-terceiros/034.jpg', '/img/processos/controle-de-terceiros/035.jpg']
  WHERE titulo ILIKE '%Pagamento de Motoristas Agregados%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/controle-abastecimento/001.jpg', '/img/processos/controle-abastecimento/002.jpg', '/img/processos/controle-abastecimento/003.jpg', '/img/processos/controle-abastecimento/004.jpg', '/img/processos/controle-abastecimento/005.jpg', '/img/processos/controle-abastecimento/006.jpg', '/img/processos/controle-abastecimento/007.jpg', '/img/processos/controle-abastecimento/008.jpg', '/img/processos/controle-abastecimento/009.jpg', '/img/processos/controle-abastecimento/010.jpg', '/img/processos/controle-abastecimento/011.jpg', '/img/processos/controle-abastecimento/012.jpg', '/img/processos/controle-abastecimento/013.jpg', '/img/processos/controle-abastecimento/014.jpg', '/img/processos/controle-abastecimento/015.jpg', '/img/processos/controle-abastecimento/016.jpg', '/img/processos/controle-abastecimento/017.jpg', '/img/processos/controle-abastecimento/018.jpg', '/img/processos/controle-abastecimento/019.jpg', '/img/processos/controle-abastecimento/020.jpg', '/img/processos/controle-abastecimento/021.jpg', '/img/processos/controle-abastecimento/022.jpg', '/img/processos/controle-abastecimento/023.jpg', '/img/processos/controle-abastecimento/024.jpg', '/img/processos/controle-abastecimento/025.jpg', '/img/processos/controle-abastecimento/026.jpg', '/img/processos/controle-abastecimento/027.jpg', '/img/processos/controle-abastecimento/028.jpg']
  WHERE titulo ILIKE '%Controle de Abastecimento Interno%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/controle-abastecimento/001.jpg', '/img/processos/controle-abastecimento/002.jpg', '/img/processos/controle-abastecimento/003.jpg', '/img/processos/controle-abastecimento/004.jpg', '/img/processos/controle-abastecimento/005.jpg', '/img/processos/controle-abastecimento/006.jpg', '/img/processos/controle-abastecimento/007.jpg', '/img/processos/controle-abastecimento/008.jpg', '/img/processos/controle-abastecimento/009.jpg', '/img/processos/controle-abastecimento/010.jpg', '/img/processos/controle-abastecimento/011.jpg', '/img/processos/controle-abastecimento/012.jpg', '/img/processos/controle-abastecimento/013.jpg', '/img/processos/controle-abastecimento/014.jpg', '/img/processos/controle-abastecimento/015.jpg', '/img/processos/controle-abastecimento/016.jpg', '/img/processos/controle-abastecimento/017.jpg', '/img/processos/controle-abastecimento/018.jpg', '/img/processos/controle-abastecimento/019.jpg', '/img/processos/controle-abastecimento/020.jpg', '/img/processos/controle-abastecimento/021.jpg', '/img/processos/controle-abastecimento/022.jpg', '/img/processos/controle-abastecimento/023.jpg', '/img/processos/controle-abastecimento/024.jpg', '/img/processos/controle-abastecimento/025.jpg', '/img/processos/controle-abastecimento/026.jpg', '/img/processos/controle-abastecimento/027.jpg', '/img/processos/controle-abastecimento/028.jpg']
  WHERE titulo ILIKE '%Controle de Abastecimento Externo%';

UPDATE public.processos SET galeria = ARRAY['/img/processos/wms/001.jpg', '/img/processos/wms/002.jpg', '/img/processos/wms/003.jpg', '/img/processos/wms/004.jpg', '/img/processos/wms/005.jpg', '/img/processos/wms/006.jpg', '/img/processos/wms/007.jpg', '/img/processos/wms/008.jpg', '/img/processos/wms/009.jpg', '/img/processos/wms/010.jpg', '/img/processos/wms/011.jpg', '/img/processos/wms/012.jpg', '/img/processos/wms/013.jpg', '/img/processos/wms/014.jpg', '/img/processos/wms/015.jpg', '/img/processos/wms/016.jpg', '/img/processos/wms/017.jpg', '/img/processos/wms/018.jpg', '/img/processos/wms/019.jpg', '/img/processos/wms/020.jpg', '/img/processos/wms/021.jpg', '/img/processos/wms/022.jpg', '/img/processos/wms/023.jpg', '/img/processos/wms/024.jpg', '/img/processos/wms/025.jpg', '/img/processos/wms/026.jpg', '/img/processos/wms/027.jpg', '/img/processos/wms/028.jpg', '/img/processos/wms/029.jpg', '/img/processos/wms/030.jpg', '/img/processos/wms/031.jpg', '/img/processos/wms/032.jpg', '/img/processos/wms/033.jpg', '/img/processos/wms/034.jpg', '/img/processos/wms/035.jpg', '/img/processos/wms/036.jpg', '/img/processos/wms/037.jpg', '/img/processos/wms/038.jpg', '/img/processos/wms/039.jpg', '/img/processos/wms/040.jpg', '/img/processos/wms/041.jpg', '/img/processos/wms/042.jpg', '/img/processos/wms/043.jpg', '/img/processos/wms/044.jpg', '/img/processos/wms/045.jpg', '/img/processos/wms/046.jpg', '/img/processos/wms/047.jpg', '/img/processos/wms/048.jpg', '/img/processos/wms/049.jpg', '/img/processos/wms/050.jpg', '/img/processos/wms/051.jpg', '/img/processos/wms/052.jpg', '/img/processos/wms/053.jpg', '/img/processos/wms/054.jpg', '/img/processos/wms/055.jpg', '/img/processos/wms/056.jpg', '/img/processos/wms/057.jpg', '/img/processos/wms/058.jpg', '/img/processos/wms/059.jpg', '/img/processos/wms/060.jpg', '/img/processos/wms/061.jpg', '/img/processos/wms/062.jpg', '/img/processos/wms/063.jpg', '/img/processos/wms/064.jpg', '/img/processos/wms/065.jpg', '/img/processos/wms/066.jpg', '/img/processos/wms/067.jpg', '/img/processos/wms/068.jpg', '/img/processos/wms/069.jpg', '/img/processos/wms/070.jpg', '/img/processos/wms/071.jpg', '/img/processos/wms/072.jpg', '/img/processos/wms/073.jpg', '/img/processos/wms/074.jpg', '/img/processos/wms/075.jpg']
  WHERE titulo ILIKE '%Controle de Pagamentos de Tributos%';

UPDATE public.processos SET galeria = ARRAY[]::text[]
  WHERE titulo ILIKE '%Instalacao de Certificado%';

UPDATE public.processos SET galeria = ARRAY[]::text[]
  WHERE titulo ILIKE '%Instalação de Certificado%';
